import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blue Bird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/static/favicon.ico" />
      </Head>
    </>
  );
}
