import BirdVideo from "@/components/BirdVideo/BirdVideo";
import Contact from "@/components/Contacts/Contact";
import Events from "@/components/Events/Events";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import Hero from "@/components/Hero/Hero";
import Memories from "@/components/Memories/Memories";
import Head from "next/head";
import Modal from "@/components/Modal/ModalConnect";
import CardsBlock from "@/components/CardsBlock/CardsBlock";

export default function Home() {
  return (
    <>
      <Head>
        <title>Blue Bird</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/static/favicon.ico" />
      </Head>
      <Modal />
      <Hero />
      <Memories />
      <CardsBlock/>
      <Events />
      <BirdVideo/>
      <Contact />
    </>
  );
}
